# Generated by Django 6.0.5 on 2026-05-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_remove_appointment_date_time_appointment_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
