# Generated by Django 6.0.5 on 2026-05-17 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_appointment_date_time'),
        ('servicios', '0003_servicepackage_image_alter_servicepackage_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.coupon'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='discount_applied',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
