# Generated by Django 6.0.5 on 2026-05-18 04:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_appointment_coupon_appointment_discount_applied_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CosmiatricAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(help_text='Acciones realizadas durante el servicio')),
                ('products_used', models.TextField(help_text='Productos aplicados (ej. Ácido Hialurónico, Limpiador X)')),
                ('reaction', models.CharField(choices=[('positive', 'Positiva/Normal'), ('neutral', 'Leve enrojecimiento'), ('negative', 'Reacción adversa/Alergia')], default='positive', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='annotation', to='citas.appointment')),
            ],
            options={
                'verbose_name': 'Anotación Cosmeátrica',
                'verbose_name_plural': 'Anotaciones Cosmeátricas',
            },
        ),
    ]
