# Generated by Django 6.0.6 on 2026-06-06 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_cosmiatricannotation'),
        ('servicios', '0005_alter_serviceschedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='servicios.serviceschedule'),
        ),
    ]
