# Generated by Django 5.2.13 on 2026-04-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('cliente', 'Paciente/Cliente'), ('cosmiatra', 'Cosmiatra/Especialista')], default='cliente', max_length=20),
        ),
        migrations.AddField(
            model_name='cosmiatra',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
