# Generated by Django 6.0.5 on 2026-05-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('cliente', 'Paciente/Cliente'), ('cosmiatra', 'Cosmiatra/Especialista'), ('secretaria', 'Secretaria/Recepcionista')], default='cliente', max_length=20),
        ),
    ]
