# Generated by Django 6.0.5 on 2026-05-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_clientprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True),
        ),
    ]
