# Generated by Django 6.0.6 on 2026-06-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_clientprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
