# Generated by Django 6.0.5 on 2026-06-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_clientprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='glow_points',
            field=models.IntegerField(default=0),
        ),
    ]
