# Generated by Django 5.2.13 on 2026-04-26 04:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(default='Estética', max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_minutes', models.IntegerField()),
                ('image_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Paquete de Servicio',
                'verbose_name_plural': 'Paquetes de Servicios',
            },
        ),
    ]
