# Generated by Django 6.0.5 on 2026-05-16 17:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
        ('usuarios', '0003_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('cosmiatra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='usuarios.cosmiatra')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='servicios.servicepackage')),
            ],
            options={
                'verbose_name': 'Horario de Servicio',
                'verbose_name_plural': 'Horarios de Servicios',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
