# Generated by Django 6.0.5 on 2026-05-17 21:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_serviceschedule'),
        ('usuarios', '0004_alter_clientprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.IntegerField(default=1)),
                ('current_uses', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='usuarios.clientprofile')),
            ],
            options={
                'verbose_name': 'Cupón de Descuento',
                'verbose_name_plural': 'Cupones de Descuento',
            },
        ),
    ]
