# Generated by Django 6.0.6 on 2026-06-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_servicereview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceschedule',
            options={'verbose_name': 'Horario de Servicio', 'verbose_name_plural': 'Horarios de Servicios'},
        ),
        migrations.RenameField(
            model_name='serviceschedule',
            old_name='is_booked',
            new_name='is_paused',
        ),
        migrations.AddField(
            model_name='serviceschedule',
            name='days_of_week',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='serviceschedule',
            name='paused_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceschedule',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
