# Generated by Django 6.0.5 on 2026-06-06 07:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_alter_serviceschedule_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('glow_points_cost', models.IntegerField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_mock', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_approved_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='usage_limit_per_user',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='post_care',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='protocol_benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicereview',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicereview',
            name='staff_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceschedule',
            name='overtime_justification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('delivered', 'Entregado')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.rewardproduct')),
            ],
        ),
    ]
