# Generated by Django 6.0.5 on 2026-06-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_rewardproduct_coupon_is_approved_by_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productredemption',
            name='delivery_image',
            field=models.ImageField(blank=True, null=True, upload_to='deliveries/'),
        ),
    ]
