# Generated by Django 6.0.5 on 2026-06-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_productredemption_delivery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_unlimited',
            field=models.BooleanField(default=False),
        ),
    ]
