# Generated by Django 6.0.5 on 2026-06-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_coupon_is_unlimited'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
