# Generated by Django 6.0.5 on 2026-06-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_rewardproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackage',
            name='glow_points_reward',
            field=models.IntegerField(default=50),
        ),
    ]
